version: '3'
services:
      web:
        build: .
        volumes:
         - /usr/src/app/App
        ports:
          - "80:3000"
        depends_on:
          - mongo
      mongo:
        image: mongo
        ports:
          - "27017:27017"
        volumes:
            - ./data:/data/db